@Echo Off
call xcopy "..\europe1\shapes\AisGill.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\AisGill.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\church1.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\church1.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\cottage1.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\cottage1.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\DryStoneWall50m.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\DryStoneWall50m.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\farmhouse1_.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\farmhouse1_.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\housesemi_four.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\housesemi_four.sd" .\Shapes\ /Y
call xcopy "..\japan1\shapes\Jp1Car01.s" .\Shapes\ /Y
call xcopy "..\japan1\shapes\Jp1Car01.sd" .\Shapes\ /Y
call xcopy "..\japan1\shapes\JP1GreenFla.s" .\Shapes\ /Y
call xcopy "..\japan1\shapes\JP1PerRedSp.s" .\Shapes\ /Y
call xcopy "..\japan1\shapes\JP1PerRedSp2.s" .\Shapes\ /Y
call xcopy "..\japan1\shapes\JP1PerRedSp2.sd" .\Shapes\ /Y
call xcopy "..\japan1\shapes\JP1PetrolStation.s" .\Shapes\ /Y
call xcopy "..\japan1\shapes\JP1PetrolStation.sd" .\Shapes\ /Y
call xcopy "..\japan2\shapes\JP1ResumeSp.s" .\Shapes\ /Y
call xcopy "..\japan1\shapes\JP1ResumeSp.sd" .\Shapes\ /Y
call xcopy "..\japan1\shapes\JP1streetlight1.s" .\Shapes\ /Y
call xcopy "..\japan1\shapes\JP1streetlight1.sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\JP1tunnel1t.s" .\Shapes\ /Y
call xcopy "..\europe2\shapes\JP1tunnel1t.sd" .\Shapes\ /Y
call xcopy "..\japan1\shapes\JP1YelloFla.s" .\Shapes\ /Y
call xcopy "..\japan2\shapes\JP2Bush2.s" .\Shapes\ /Y
call xcopy "..\europe2\shapes\JP2Bush2.sd" .\Shapes\ /Y
call xcopy "..\japan2\shapes\JP2Bush3.s" .\Shapes\ /Y
call xcopy "..\europe2\shapes\JP2Bush3.sd" .\Shapes\ /Y
call xcopy "..\japan2\shapes\JP2shutgar.s" .\Shapes\ /Y
call xcopy "..\japan2\shapes\JP2shutgar.sd" .\Shapes\ /Y
call xcopy "..\japan2\shapes\JP2Tree1.s" .\Shapes\ /Y
call xcopy "..\japan2\shapes\JP2Tree1.sd" .\Shapes\ /Y
call xcopy "..\japan2\shapes\JP2Tree3.s" .\Shapes\ /Y
call xcopy "..\japan2\shapes\JP2Tree3.sd" .\Shapes\ /Y
call xcopy "..\japan2\shapes\JP2Wier2.s" .\Shapes\ /Y
call xcopy "..\japan2\shapes\JP2Wier2.sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\OE60Mwall.S" .\Shapes\ /Y
call xcopy "..\europe2\shapes\OE60Mwall.Sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\OEbrickpile.S" .\Shapes\ /Y
call xcopy "..\europe2\shapes\OEbrickpile.Sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\OEChurch.s" .\Shapes\ /Y
call xcopy "..\europe2\shapes\OEChurch.sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\OEfamhaus.S" .\Shapes\ /Y
call xcopy "..\europe2\shapes\OEfamhaus.Sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\OEIndbuild04.s" .\Shapes\ /Y
call xcopy "..\europe2\shapes\OEIndbuild04.sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\OErubpile.S" .\Shapes\ /Y
call xcopy "..\europe2\shapes\OErubpile.Sd" .\Shapes\ /Y
call xcopy "..\usa1\shapes\overlying_freeway2.s" .\Shapes\ /Y
call xcopy "..\usa1\shapes\overlying_freeway2.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\PortakabinRed.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\PortakabinRed.sd" .\Shapes\ /Y
call xcopy "..\japan1\shapes\power_station.s" .\Shapes\ /Y
call xcopy "..\japan1\shapes\power_station.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\PUb_1500.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\PUb_1500.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\ScrapHeap.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\ScrapHeap.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\Smardale.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\Smardale.sd" .\Shapes\ /Y
call xcopy "..\japan2\shapes\TelePole.s" .\Shapes\ /Y
call xcopy "..\japan2\shapes\TelePole.sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\TeleShad.s" .\Shapes\ /Y
call xcopy "..\japan1\shapes\Tree12.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\Tree12.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\TREE3.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\TREE3.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\Tree7.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\Tree7.sd" .\Shapes\ /Y
call xcopy "..\usa1\shapes\trolley_and_car.s" .\Shapes\ /Y
call xcopy "..\usa1\shapes\trolley_and_car.sd" .\Shapes\ /Y
call xcopy "..\usa1\shapes\US1Hotel1.s" .\Shapes\ /Y
call xcopy "..\usa1\shapes\US1Hotel1.sd" .\Shapes\ /Y
call xcopy "..\usa2\shapes\US2cow.s" .\Shapes\ /Y
call xcopy "..\usa2\shapes\US2cow.sd" .\Shapes\ /Y
call xcopy "..\japan2\shapes\US2Digger.s" .\Shapes\ /Y
call xcopy "..\japan2\shapes\US2Digger.sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\US2Firs1.s" .\Shapes\ /Y
call xcopy "..\europe2\shapes\US2Firs1.sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\US2Firs2.s" .\Shapes\ /Y
call xcopy "..\europe2\shapes\US2Firs2.sd" .\Shapes\ /Y
call xcopy "..\usa2\shapes\US2IzaakLodge.s" .\Shapes\ /Y
call xcopy "..\usa2\shapes\US2IzaakLodge.sd" .\Shapes\ /Y
call xcopy "..\usa1\shapes\US2LargePrefab1.s" .\Shapes\ /Y
call xcopy "..\usa1\shapes\US2LargePrefab1.sd" .\Shapes\ /Y
call xcopy "..\usa1\shapes\US2Milepost.s" .\Shapes\ /Y
call xcopy "..\usa1\shapes\US2Milepost.sd" .\Shapes\ /Y
call xcopy "..\japan2\shapes\US2SawdustL.s" .\Shapes\ /Y
call xcopy "..\japan2\shapes\US2SawdustL.sd" .\Shapes\ /Y
call xcopy "..\usa2\shapes\US2SawdustS.s" .\Shapes\ /Y
call xcopy "..\usa2\shapes\US2SawdustS.sd" .\Shapes\ /Y
call xcopy "..\usa1\shapes\US2SawWarehouse.s" .\Shapes\ /Y
call xcopy "..\usa1\shapes\US2SawWarehouse.sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\US2ScrapYard.s" .\Shapes\ /Y
call xcopy "..\europe2\shapes\US2ScrapYard.sd" .\Shapes\ /Y
call xcopy "..\japan2\shapes\US2SmlPrefab2.s" .\Shapes\ /Y
call xcopy "..\japan2\shapes\US2SmlPrefab2.sd" .\Shapes\ /Y
call xcopy "..\usa1\shapes\US2SmlWare2.s" .\Shapes\ /Y
call xcopy "..\usa1\shapes\US2SmlWare2.sd" .\Shapes\ /Y
call xcopy "..\usa2\shapes\US2Warehouse5.s" .\Shapes\ /Y
call xcopy "..\usa1\shapes\US2Warehouse5.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\USDecidClump1.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\USDecidClump1.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\USDecidClump2.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\USDecidClump2.sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\USDecidClump3.s" .\Shapes\ /Y
call xcopy "..\usa1\shapes\USDecidClump3.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\USDecidClump4.S" .\Shapes\ /Y
call xcopy "..\europe1\shapes\USDecidClump4.Sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\USDecidTree1.s" .\Shapes\ /Y
call xcopy "..\europe2\shapes\USDecidTree1.sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\USDecidTree2.s" .\Shapes\ /Y
call xcopy "..\europe2\shapes\USDecidTree2.sd" .\Shapes\ /Y
call xcopy "..\europe2\shapes\USDecidTree3.s" .\Shapes\ /Y
call xcopy "..\europe2\shapes\USDecidTree3.sd" .\Shapes\ /Y
call xcopy "..\japan2\shapes\WireFence50m.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\WireFence50m.sd" .\Shapes\ /Y
call xcopy "..\europe1\shapes\WoodFence50m.s" .\Shapes\ /Y
call xcopy "..\europe1\shapes\WoodFence50m.sd" .\Shapes\ /Y
call xcopy "..\USA1\Textures\3BarFence.ace" .\Textures\ /y
call xcopy "..\USA1\Textures\snow\3BarFence.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\AberdeenStation.ace" .\Textures\ /y
call xcopy "..\USA1\Textures\snow\AberdeenStation.ace" .\Textures\snow\ /y
call xcopy "..\Japan1\Textures\snow\acleantrack1.ace" .\Textures\snow\ /y
call xcopy "..\Japan2\Textures\snow\acleantrack2.ace" .\Textures\snow\ /y
call xcopy "..\Europe1\Textures\ACleanTrackBase.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\snow\ATrackTunFloor.ace" .\Textures\snow\ /y
call xcopy "..\Japan2\Textures\snow\buffer.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\buffer.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\ChurchFinal.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\snow\ChurchFinal.ace" .\Textures\snow\ /y
call xcopy "..\Europe1\Textures\Night\ChurchFinal.ace" .\Textures\Night\ /y
call xcopy "..\Europe1\Textures\ChurchFinal2.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\snow\ChurchFinal2.ace" .\Textures\snow\ /y
call xcopy "..\Europe1\Textures\Night\ChurchFinal2.ace" .\Textures\Night\ /y
call xcopy "..\Europe1\Textures\CottageDoors.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\snow\CottageDoors.ace" .\Textures\snow\ /y
call xcopy "..\Europe1\Textures\CottageRoof.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\snow\CottageRoof.ace" .\Textures\snow\ /y
call xcopy "..\Europe1\Textures\CottageWall.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\snow\CottageWall.ace" .\Textures\snow\ /y
call xcopy "..\USA2\Textures\drystwall.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\farmhouse1.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\snow\farmhouse1.ace" .\Textures\snow\ /y
call xcopy "..\Europe1\Textures\Night\farmhouse1.ace" .\Textures\Night\ /y
call xcopy "..\Japan2\Textures\snow\Fences.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\Fences.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\house2_semi.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\snow\house2_semi.ace" .\Textures\snow\ /y
call xcopy "..\Europe1\Textures\Night\house2_semi.ace" .\Textures\Night\ /y
call xcopy "..\Japan1\Textures\JP1_RoadBridge_HiFence.ace" .\Textures\ /y
call xcopy "..\Japan1\Textures\Jp1Car01.ace" .\Textures\ /y
call xcopy "..\Japan1\Textures\JP1greenhouse2.ace" .\Textures\ /y
call xcopy "..\Japan1\Textures\snow\JP1greenhouse2.ace" .\Textures\snow\ /y
call xcopy "..\Japan2\Textures\snow\Jp1Hedgerows.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\JP1PetrolStation.ace" .\Textures\ /y
call xcopy "..\USA1\Textures\snow\JP1PetrolStation.ace" .\Textures\snow\ /y
call xcopy "..\Japan1\Textures\JP1ShinjukuSt.ace" .\Textures\ /s /y
call xcopy "..\Europe1\Textures\JP1SignNumbers.ace" .\Textures\ /y
call xcopy "..\Japan1\Textures\JP1streetsigns.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\snow\JP1streetsigns.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\Jp1Truck1.ace" .\Textures\ /y
call xcopy "..\Europe2\Textures\JP1tunnel1t.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\spring\JP2AutoBush2.ace" .\Textures\spring\ /y
call xcopy "..\Japan2\Textures\springsnow\JP2AutoBush2.ace" .\Textures\springsnow\ /y
call xcopy "..\Japan2\Textures\Winter\JP2AutoBush2.ace" .\Textures\Winter\ /y
call xcopy "..\Japan2\Textures\Wintersnow\JP2AutoBush2.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan2\Textures\Autumnsnow\JP2AutoBush2.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\USA1\Textures\Autumn\JP2AutoBush2.ace" .\Textures\Autumn\ /y
call xcopy "..\USA2\Textures\JP2AutoBush2.ace" .\Textures\ /s /y
call xcopy "..\Japan2\Textures\spring\JP2AutoBush3.ace" .\Textures\spring\ /y
call xcopy "..\Japan2\Textures\springsnow\JP2AutoBush3.ace" .\Textures\springsnow\ /y
call xcopy "..\Japan2\Textures\Winter\JP2AutoBush3.ace" .\Textures\Winter\ /y
call xcopy "..\Japan2\Textures\Wintersnow\JP2AutoBush3.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan2\Textures\Autumn\JP2AutoBush3.ace" .\Textures\Autumn\ /y
call xcopy "..\Japan2\Textures\Autumnsnow\JP2AutoBush3.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\Europe2\Textures\JP2Bush2.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\spring\JP2Bush2.ace" .\Textures\spring\ /y
call xcopy "..\Japan2\Textures\springsnow\JP2Bush2.ace" .\Textures\springsnow\ /y
call xcopy "..\Japan2\Textures\Wintersnow\JP2Bush2.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan2\Textures\Autumn\JP2Bush2.ace" .\Textures\Autumn\ /y
call xcopy "..\Japan2\Textures\Autumnsnow\JP2Bush2.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\Japan2\Textures\spring\JP2Bush3.ace" .\Textures\spring\ /y
call xcopy "..\Japan2\Textures\springsnow\JP2Bush3.ace" .\Textures\springsnow\ /y
call xcopy "..\Japan2\Textures\Wintersnow\JP2Bush3.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan2\Textures\Autumn\JP2Bush3.ace" .\Textures\Autumn\ /y
call xcopy "..\Japan2\Textures\Autumnsnow\JP2Bush3.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\Japan2\Textures\JP2Tree1.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\spring\JP2Tree1.ace" .\Textures\spring\ /y
call xcopy "..\Japan2\Textures\springsnow\JP2Tree1.ace" .\Textures\springsnow\ /y
call xcopy "..\Japan2\Textures\Winter\JP2Tree1.ace" .\Textures\Winter\ /y
call xcopy "..\Japan2\Textures\Wintersnow\JP2Tree1.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan2\Textures\Autumn\JP2Tree1.ace" .\Textures\Autumn\ /y
call xcopy "..\Japan2\Textures\Autumnsnow\JP2Tree1.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\Japan2\Textures\JP2Tree3.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\spring\JP2Tree3.ace" .\Textures\spring\ /y
call xcopy "..\Japan2\Textures\springsnow\JP2Tree3.ace" .\Textures\springsnow\ /y
call xcopy "..\Japan2\Textures\Winter\JP2Tree3.ace" .\Textures\Winter\ /y
call xcopy "..\Japan2\Textures\Wintersnow\JP2Tree3.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan2\Textures\Autumn\JP2Tree3.ace" .\Textures\Autumn\ /y
call xcopy "..\Japan2\Textures\Autumnsnow\JP2Tree3.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\Japan2\Textures\JP2wier2.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\light.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\snow\light.ace" .\Textures\snow\ /y
call xcopy "..\Europe2\Textures\OE20Mwalltex.ace" .\Textures\ /y
call xcopy "..\Europe2\Textures\snow\OE20Mwalltex.ace" .\Textures\snow\ /y
call xcopy "..\Europe2\Textures\OEbrickpiletex.ace" .\Textures\ /y
call xcopy "..\Europe2\Textures\snow\OEbrickpiletex.ace" .\Textures\snow\ /y
call xcopy "..\Europe2\Textures\snow\OEChurch.ace" .\Textures\snow\ /y
call xcopy "..\Europe2\Textures\OEfamhaus.ace" .\Textures\ /y
call xcopy "..\Europe2\Textures\snow\OEfamhaus.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\OEHotel2.ace" .\Textures\ /y
call xcopy "..\USA1\Textures\snow\OEHotel2.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\overlying_freeway2.ace" .\Textures\ /y
call xcopy "..\USA1\Textures\snow\overlying_freeway2.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\Portakabin.ace" .\Textures\ /y
call xcopy "..\USA1\Textures\snow\Portakabin.ace" .\Textures\snow\ /y
call xcopy "..\Japan2\Textures\snow\power_station.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\power_station.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\Pub_LBP.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\snow\Pub_LBP.ace" .\Textures\snow\ /y
call xcopy "..\Europe1\Textures\pub_sideLBP.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\snow\pub_sideLBP.ace" .\Textures\snow\ /y
call xcopy "..\Japan2\Textures\snow\road.ace" .\Textures\snow\ /y
call xcopy "..\Japan2\Textures\snow\road2lane.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\road2lane.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\snow\road2lane_dt.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\road2lane_dt.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\snow\road2LaneT.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\road2LaneT.ace" .\Textures\ /y
call xcopy "..\USA2\Textures\road2LaneT_dt.ace" .\Textures\ /y
call xcopy "..\USA2\Textures\snow\road2LaneT_dt.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\road2Lcross.ace" .\Textures\ /y
call xcopy "..\USA1\Textures\snow\road2Lcross.ace" .\Textures\snow\ /y
call xcopy "..\Japan2\Textures\snow\road4lane.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\road4lane.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\snow\road4Lcross.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\road4Lcross.ace" .\Textures\ /y
call xcopy "..\Europe2\Textures\rubpiletex.ace" .\Textures\ /y
call xcopy "..\Europe2\Textures\snow\rubpiletex.ace" .\Textures\snow\ /y
call xcopy "..\Japan2\Textures\snow\ScrapHeap1.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\ScrapHeap1.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\shutgartex.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\snow\shutgartex.ace" .\Textures\snow\ /y
call xcopy "..\Europe1\Textures\SignNumbers.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\snow\StoneArch.ace" .\Textures\snow\ /y
call xcopy "..\Europe1\Textures\snow\StoneGrey.ace" .\Textures\snow\ /y
call xcopy "..\Europe1\Textures\teleshadow.ace" .\Textures\ /y
call xcopy "..\USA1\Textures\telpole.ace" .\Textures\ /y
call xcopy "..\USA1\Textures\tractor.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\spring\tree1.ace" .\Textures\spring\ /y
call xcopy "..\Europe1\Textures\springsnow\tree1.ace" .\Textures\springsnow\ /y
call xcopy "..\Europe2\Textures\Wintersnow\tree1.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan1\Textures\Autumn\tree1.ace" .\Textures\Autumn\ /y
call xcopy "..\Japan1\Textures\Autumnsnow\tree1.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\Japan2\Textures\spring\Tree11.ace" .\Textures\spring\ /y
call xcopy "..\Japan2\Textures\springsnow\Tree11.ace" .\Textures\springsnow\ /y
call xcopy "..\Japan2\Textures\Winter\Tree11.ace" .\Textures\Winter\ /y
call xcopy "..\Japan2\Textures\Wintersnow\Tree11.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan2\Textures\Autumn\Tree11.ace" .\Textures\Autumn\ /y
call xcopy "..\Japan2\Textures\Autumnsnow\Tree11.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\Japan2\Textures\TREE4.ACE" .\Textures\ /y
call xcopy "..\Japan2\Textures\spring\TREE4.ACE" .\Textures\spring\ /y
call xcopy "..\Japan2\Textures\springsnow\TREE4.ACE" .\Textures\springsnow\ /y
call xcopy "..\Japan2\Textures\Winter\TREE4.ACE" .\Textures\Winter\ /y
call xcopy "..\Japan2\Textures\Wintersnow\TREE4.ACE" .\Textures\Wintersnow\ /y
call xcopy "..\Japan2\Textures\Autumn\TREE4.ACE" .\Textures\Autumn\ /y
call xcopy "..\Japan2\Textures\Autumnsnow\TREE4.ACE" .\Textures\Autumnsnow\ /y
call xcopy "..\Europe1\Textures\springsnow\Tree7.ace" .\Textures\springsnow\ /y
call xcopy "..\Europe1\Textures\Winter\Tree7.ace" .\Textures\Winter\ /y
call xcopy "..\Europe2\Textures\Wintersnow\Tree7.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan1\Textures\spring\Tree7.ace" .\Textures\spring\ /y
call xcopy "..\Japan1\Textures\Autumn\Tree7.ace" .\Textures\Autumn\ /y
call xcopy "..\Japan1\Textures\Autumnsnow\Tree7.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\Japan2\Textures\Wintersnow\Tree8.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan2\Textures\Autumn\Tree8.ace" .\Textures\Autumn\ /y
call xcopy "..\Japan2\Textures\Autumnsnow\Tree8.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\USA2\Textures\Tree8.ace" .\Textures\ /y
call xcopy "..\USA2\Textures\spring\Tree8.ace" .\Textures\spring\ /y
call xcopy "..\USA2\Textures\springsnow\Tree8.ace" .\Textures\springsnow\ /y
call xcopy "..\Japan2\Textures\TREEMD.ACE" .\Textures\ /y
call xcopy "..\Japan2\Textures\spring\TREEMD.ACE" .\Textures\spring\ /y
call xcopy "..\Japan2\Textures\springsnow\TREEMD.ACE" .\Textures\springsnow\ /y
call xcopy "..\USA1\Textures\trolley_car.ace" .\Textures\ /y
call xcopy "..\Europe2\Textures\tunnel_single.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\UKSignNumbers.ace" .\Textures\ /y
call xcopy "..\Europe1\Textures\spring\UKTreeLine.ace" .\Textures\spring\ /y
call xcopy "..\Europe1\Textures\Winter\UKTreeLine.ace" .\Textures\Winter\ /y
call xcopy "..\Europe1\Textures\Autumnsnow\UKTreeLine.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\Japan1\Textures\UKTreeLine.ace" .\Textures\ /y
call xcopy "..\Japan1\Textures\springsnow\UKTreeLine.ace" .\Textures\springsnow\ /y
call xcopy "..\Japan1\Textures\Wintersnow\UKTreeLine.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan1\Textures\Autumn\UKTreeLine.ace" .\Textures\Autumn\ /y
call xcopy "..\Japan2\Textures\US2AutoFir1.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\spring\US2AutoFir1.ace" .\Textures\spring\ /y
call xcopy "..\Japan2\Textures\springsnow\US2AutoFir1.ace" .\Textures\springsnow\ /y
call xcopy "..\Japan2\Textures\Winter\US2AutoFir1.ace" .\Textures\Winter\ /y
call xcopy "..\Japan2\Textures\Wintersnow\US2AutoFir1.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan2\Textures\Autumnsnow\US2AutoFir1.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\USA2\Textures\Autumn\US2AutoFir1.ace" .\Textures\Autumn\ /y
call xcopy "..\Japan2\Textures\US2AutoFir2.ace" .\Textures\ /y
call xcopy "..\USA1\Textures\spring\US2AutoFir2.ace" .\Textures\spring\ /y
call xcopy "..\USA1\Textures\springsnow\US2AutoFir2.ace" .\Textures\springsnow\ /y
call xcopy "..\USA1\Textures\Winter\US2AutoFir2.ace" .\Textures\Winter\ /y
call xcopy "..\USA1\Textures\Wintersnow\US2AutoFir2.ace" .\Textures\Wintersnow\ /y
call xcopy "..\USA2\Textures\Autumn\US2AutoFir2.ace" .\Textures\Autumn\ /y
call xcopy "..\USA2\Textures\US2cow.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\US2Digger.ace" .\Textures\ /y
call xcopy "..\Europe2\Textures\spring\US2Fir3.ace" .\Textures\spring\ /y
call xcopy "..\Europe2\Textures\springsnow\US2Fir3.ace" .\Textures\springsnow\ /y
call xcopy "..\Europe2\Textures\Winter\US2Fir3.ace" .\Textures\Winter\ /y
call xcopy "..\Europe2\Textures\Wintersnow\US2Fir3.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Europe2\Textures\Autumn\US2Fir3.ace" .\Textures\Autumn\ /y
call xcopy "..\Europe2\Textures\Autumnsnow\US2Fir3.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\Europe2\Textures\spring\US2Firs2.ace" .\Textures\spring\ /y
call xcopy "..\Europe2\Textures\springsnow\US2Firs2.ace" .\Textures\springsnow\ /y
call xcopy "..\Europe2\Textures\Winter\US2Firs2.ace" .\Textures\Winter\ /y
call xcopy "..\Europe2\Textures\Wintersnow\US2Firs2.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Europe2\Textures\Autumn\US2Firs2.ace" .\Textures\Autumn\ /y
call xcopy "..\Europe2\Textures\Autumnsnow\US2Firs2.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\USA2\Textures\US2IzaakHotel.ace" .\Textures\ /y
call xcopy "..\USA2\Textures\snow\US2IzaakHotel.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\US2Milepost.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\US2Sawdustpile.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\snow\US2Sawdustpile.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\snow\US2Sawmill.ace" .\Textures\snow\ /y
call xcopy "..\USA2\Textures\US2Sawmill.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\US2Scrapyard.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\snow\US2Scrapyard.ace" .\Textures\snow\ /y
call xcopy "..\Japan2\Textures\US2Shelby.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\snow\US2Shelby.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\US2SmlWare.ace" .\Textures\ /y
call xcopy "..\USA1\Textures\snow\US2SmlWare.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\US2ThriftSt2.ace" .\Textures\ /y
call xcopy "..\USA1\Textures\snow\US2ThriftSt2.ace" .\Textures\snow\ /y
call xcopy "..\USA1\Textures\snow\US2Warehouse1.ace" .\Textures\snow\ /y
call xcopy "..\USA2\Textures\US2Warehouse1.ace" .\Textures\ /y
call xcopy "..\USA1\Textures\snow\Us2Warehouse6.ace" .\Textures\snow\ /y
call xcopy "..\USA2\Textures\Us2Warehouse6.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\US2WhistlePost.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\US2WhistlePost2.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\USDecidTree1.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\spring\USDecidTree1.ace" .\Textures\spring\ /y
call xcopy "..\Japan2\Textures\springsnow\USDecidTree1.ace" .\Textures\springsnow\ /y
call xcopy "..\Japan2\Textures\Wintersnow\USDecidTree1.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan2\Textures\Autumn\USDecidTree1.ace" .\Textures\Autumn\ /y
call xcopy "..\Japan2\Textures\Autumnsnow\USDecidTree1.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\Japan2\Textures\USDecidTree2.ace" .\Textures\ /y
call xcopy "..\Japan2\Textures\spring\USDecidTree2.ace" .\Textures\spring\ /y
call xcopy "..\Japan2\Textures\springsnow\USDecidTree2.ace" .\Textures\springsnow\ /y
call xcopy "..\Japan2\Textures\Wintersnow\USDecidTree2.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan2\Textures\Autumn\USDecidTree2.ace" .\Textures\Autumn\ /y
call xcopy "..\Japan2\Textures\Autumnsnow\USDecidTree2.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\Japan2\Textures\springsnow\USDecidTree3.ace" .\Textures\springsnow\ /y
call xcopy "..\Japan2\Textures\Wintersnow\USDecidTree3.ace" .\Textures\Wintersnow\ /y
call xcopy "..\Japan2\Textures\Autumn\USDecidTree3.ace" .\Textures\Autumn\ /y
call xcopy "..\Japan2\Textures\Autumnsnow\USDecidTree3.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\USA2\Textures\USDecidTree3.ace" .\Textures\ /y
call xcopy "..\USA2\Textures\spring\USDecidTree3.ace" .\Textures\spring\ /y
call xcopy "..\USA1\Textures\USDecidTrees1.ace" .\Textures\ /y
call xcopy "..\USA1\Textures\Wintersnow\USDecidTrees1.ace" .\Textures\Wintersnow\ /y
call xcopy "..\USA1\Textures\Autumn\USDecidTrees1.ace" .\Textures\Autumn\ /y
call xcopy "..\USA1\Textures\Autumnsnow\USDecidTrees1.ace" .\Textures\Autumnsnow\ /y
call xcopy "..\USA1\TerrTex\microtex.ace" .\TerrTex\ /s /y
call xcopy "..\USA2\TerrTex\US2Farmland1.ace" .\TerrTex\ /s /y
call xcopy "..\USA2\TerrTex\US2Farmland2.ace" .\TerrTex\ /s /y
call xcopy "..\USA2\TerrTex\US2HalfGrass-Scrub.ace" .\TerrTex\ /s /y
call xcopy "..\USA2\TerrTex\US2HalfPRock-Scrub.ace" .\TerrTex\ /s /y
call xcopy "..\USA2\TerrTex\US2Scrub1.ace" .\TerrTex\ /s /y
call xcopy "..\USA2\TerrTex\US2Scrub2.ace" .\TerrTex\ /s /y
call xcopy "..\USA2\TerrTex\US2Whitefish.ace" .\TerrTex\ /s /y
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\Forest.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\forest02_basic.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\gndtex16.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\graintex.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\JP2FolRock.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\JP2ForRock.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\meadow08_basic.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\ploughedfield08_basic.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\RS-roc03.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\RS-roc10.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\stubble08_basic.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\terrain.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\US2Farmland1.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\US2Farmland2.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\US2HalfGrass-Scrub.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\US2HalfPRock-Scrub.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\US2Scrub1.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\US2Scrub2.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\US2Whitefish.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\vegetable08_basic.ace"
copy "..\USA2\TerrTex\Snow\US2TarGnd.ace" ".\Terrtex\Snow\vignes.ace"

call Xcopy "..\europe1\Sound\ingame.sms" .\Sound\ /s /y
call Xcopy "..\europe1\Sound\signal.sms" .\Sound\ /s /y
call Xcopy "..\USA2\Sound\sig_barrierc.wav" .\Sound\ /s /y
call Xcopy "..\USA2\Sound\sig_barriero.wav" .\Sound\ /s /y
call Xcopy "..\europe1\Sound\sig_semaphore.wav" .\Sound\ /s /y
call xcopy "..\..\Template\Envfiles\Textures\daysky.ace" .\Envfiles\Textures\ /y
call xcopy "..\..\Template\Envfiles\Textures\moon.ace" .\Envfiles\Textures\ /y
call xcopy "..\..\Template\Envfiles\Textures\rain.ace" .\Envfiles\Textures\ /y
call xcopy "..\..\Template\Envfiles\Textures\rainsky.ace" .\Envfiles\Textures\ /y
call xcopy "..\..\Template\Envfiles\Textures\rainskylo.ace" .\Envfiles\Textures\ /y
call xcopy "..\..\Template\Envfiles\Textures\skylow.ace" .\Envfiles\Textures\ /y
call xcopy "..\..\Template\Envfiles\Textures\snow.ace" .\Envfiles\Textures\ /y
call xcopy "..\..\Template\Envfiles\Textures\snowsky.ace" .\Envfiles\Textures\ /y
call xcopy "..\..\Template\Envfiles\Textures\snowskylo.ace" .\Envfiles\Textures\ /y
call xcopy "..\..\Template\Envfiles\Textures\starsky.ace" .\Envfiles\Textures\ /y
call xcopy "..\..\Template\Envfiles\Textures\sun.ace" .\Envfiles\Textures\ /y
call xcopy "..\..\Template\Envfiles\Textures\test.ace" .\Envfiles\Textures\ /y
call xcopy "..\..\Template\Envfiles\Textures\waterbot.ace" .\Envfiles\Textures\ /y
call xcopy "..\..\Template\Envfiles\Textures\watermid.ace" .\Envfiles\Textures\ /y
call xcopy "..\..\Template\Envfiles\Textures\watertop.ace" .\Envfiles\Textures\ /y
call Xcopy ".\Textures\_txt10_TR-MagMerci.ACE" .\Textures\Snow\ /y
call Xcopy ".\Textures\7concrete.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\7PANY_in.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\7Plate.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\7ROOF.ACE" .\Textures\Snow\ /y
call Xcopy ".\Textures\7sawmill.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\7sawmill2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\7sawmill3.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\7smokestack5.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACacierconstruction02.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACautoscenic.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACbar.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACbarriéreSNCF.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACbeton06.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACclotureSNCF.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACdab.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACferme01.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACferme03.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACgardecorps02.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\AClinge.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACmagasinville05.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACmaisonvillage01a.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACmaisonvillage01b.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACmaisonvillage01c.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACmaisonvillage02a.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACmurmacpierre04.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACpavillon01a.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACpavillon02.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACpavillon03.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACpavillon03b.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACpavillon04.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACpavillon06.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACreditagricole.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ACtunnelpierre.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\afs00500.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\an9.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\annexh.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\avre2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\BAGNI3.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\barself.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\batpis.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Betontreppe.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\BlocMaisons.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Bluebells.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Boden06.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\boglia2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Boulang.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\boulit.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\br50.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\brdep.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\brigest.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Camini.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\cascatin.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\casge7.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\casge8.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\caslava.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\caslig0.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\caslig2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\caslig7.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\casluca.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\casluch.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\casrenz.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\casturla.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\cavib.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\chatviln.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\chezvous.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\clichy.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\concas.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\cortila.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\DBa1.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\DBa2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\DBa6.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\DBlank.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\depobb.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\DHBau3.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\DTEsso.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\DTEsso1.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\DWB2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0001.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0002.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0003.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0003a.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0003b.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0004.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0005.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0006.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0007.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0008.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0009.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0010.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0011.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0012.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0013.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0902.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Edi0903.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\EDladr01.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\EDladr02.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\EDladr03.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\EDladr04.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\EDZJAlm22.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\EK_Haus.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\faite.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\fasa1.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\fauba.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\faubb.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\fond1.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\garenau.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\gebr5.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\gebri4.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\GH_01.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\GH_02.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\GH_base.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\gl01.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\GL-Haus2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\graintex.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\grass-jadegreen0,4_B.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Gravier.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\grille.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\hallemarchand01.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\hallemarchand02.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\hallemarchand03.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Hofer16.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\HPDepot01.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\HPImmeuble01.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\HPImmeuble02.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\HPImmeuble03.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\HPImmeuble04.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\HPtex21.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\HPtex22.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\HPtex23.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ibis.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\idealcas.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Iglesia_romanica_03.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\IJ_caravan.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\IJ_hedgerow.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\IJ_tents.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\IJ_vwcamper2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\IMM03.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\jauneluc.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\kioska1.ACE" .\Textures\Snow\ /y
call Xcopy ".\Textures\kioska2.ACE" .\Textures\Snow\ /y
call Xcopy ".\Textures\kioska3.ACE" .\Textures\Snow\ /y
call Xcopy ".\Textures\kioska4.ACE" .\Textures\Snow\ /y
call Xcopy ".\Textures\Liberty-1.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Liberty-1bis.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Liberty-2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Liberty-3.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Liberty-4.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Liberty-5.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\lucjaune.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Magasins.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\maiscred.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\maisdama.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\maisdamb.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\maisdamc.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\maislucB.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MAISON.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\maisonB.ACE" .\Textures\Snow\ /y
call Xcopy ".\Textures\maisonC.ACE" .\Textures\Snow\ /y
call Xcopy ".\Textures\marquage.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\marte.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Mauer01.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MillDoor.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MillFurn1.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MillName.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MillShip.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MillStacks.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MillTank.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\minigare01.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MLW_Glas1.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MLW_Holz1.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MLWfabrik1.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MLWfabrik2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MM99.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MR_TEX_049.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MR_TEX_051.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MR_TEX_057.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MR_TEX_059.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MR_TEX_070.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MR_TEX_074.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MR_TEX_128.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MR_TEX_129.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MSForestline62A.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MSForestline73.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\MSForestlineExtra73.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\mtrga.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\murBrique2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\mur-meuliere.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\murpuba.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\murvoute.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\NCR_1st-Dst-block.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\NCR_1stDstTile.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\NCR_1st-Est.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\NCR_1st-Hst-block.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\NCR_1st-HstTile.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\NCR_DstApt.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\NCR_GRNWhse.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\nervi2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\nervisc2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\nerviscal.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ombrello.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\p005.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\pava.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\phares.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\pp01.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\pp80.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\ppopel.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_KB_PAN5A.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_KB_PAN5B.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_KB_PAN5C.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_OVI1.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_OVI2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_SZHAZ01A.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_SZHAZ01B.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_SZHAZ01C.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_SZHAZ01D.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ01A.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ01B.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ01C.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ03C.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ03D.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ05B.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ06B.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ06C.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ07B.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ08A.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ08B.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ14A.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ14B.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ14C.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ14D.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ14E.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\PTR_TGHAZ67A.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Publi2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Publi3.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\reihenhaus2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\remise.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\remise02.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\rosesab.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\rst_h12.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\rst_h16.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\rst_haus_0002.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\rst_haus_0002-d.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\rst_haus_0002-d-s.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\rst_haus_0002-g.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\rst_haus_0002-l.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\rst_haus_0002-m.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\RVCHGMaisonsPN1.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\RVCHGMaisonsPN2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\RVCHGRiv.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\RVFondCHG.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\scalucca.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sol10calcaire.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sol12falaisegrise.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sol13machefer.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sol14rochesable.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sol15rochesable2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sol16rochesableclair.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sol17boue.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sol18herbe.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sol1rochebrune.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sol5sablebeige.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sol6sablebrun.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sol7sablegris.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sol8sablegranuleux.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sol9cailloouteux.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\spez.ACE" .\Textures\Snow\ /y
call Xcopy ".\Textures\spez03.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\SPEZIA02.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\spezia03.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\stade.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\stone.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\stu5.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sucrerie1.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sucrerie2.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sucrerie3.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\sucrerie5.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\td_bois01.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\td_maconpierre06.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\Tetto.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\toitNoir.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\tunmtr.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\u79haus0007.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\u79haus0015.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\u79haus0040.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\u79haus0041.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\u79haus0046.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\u79haus0049.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\u79haus0051.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\u79haus0065.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\u79haus0113.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\u79haus0113b.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\usibagni.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\USIDEUT.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\usilaz.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\usimod.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\usin9.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\usine128.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\usineB.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\usisl.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\usislC.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\villB256.ACE" .\Textures\Snow\ /y
call Xcopy ".\Textures\VILLE06.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\vivaio.ACE" .\Textures\Snow\ /y
call Xcopy ".\Textures\voltair.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\woodenpylon.ace" .\Textures\Snow\ /y
call Xcopy ".\Textures\7maxwellroof.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\7Plate.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\7ROOF.ACE" .\Textures\Night\ /y
call Xcopy ".\Textures\7sawmill.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\7sawmill2.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\7sawmill3.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\7smokestack5.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\ACdab.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\Bblank.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\Betontreppe.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\BlocMaisons.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\Boden06.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\Boulang.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\casge8.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\chezvous.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\DBeton.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\DBeton1.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\DBlank.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\DWB2.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\HPGare01.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\HPImmeuble03.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\HPImmeuble04.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\HPMaison12.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\HPMaison13.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\HPmur01.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\HPtex21.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\HPtex22.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\HPtex23.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\IMM03.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\Magasins.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\Mauer01.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\MLW_Glas1.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\MLW_Holz1.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\MLWfabrik1.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\MLWfabrik2.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\MR_TEX_051.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\MR_TEX_057.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\MR_TEX_059.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\MR_TEX_070.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\mur-meuliere.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\Panneau03.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\Publi2.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\Publi3.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\rb_kloster.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\rosesab.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\RVFondCHG.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\tunmtr.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\u79haus0015.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\u79haus0051.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\usine128.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\Villawit.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\Villawit_dak.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\villB256.ACE" .\Textures\Night\ /y
call Xcopy ".\Textures\VILLE06.ace" .\Textures\Night\ /y
call Xcopy ".\Textures\vivaio.ACE" .\Textures\Night\ /y
call Xcopy ".\Textures\abete.ACE" .\Textures\Autumn\ /y
call Xcopy ".\Textures\Alzina_0.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\Alzina_1.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\arbrcha.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\BG_3.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\BG_3a.ACE" .\Textures\Autumn\ /y
call Xcopy ".\Textures\BG_6a.ACE" .\Textures\Autumn\ /y
call Xcopy ".\Textures\birch15_1_hog.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\birch15_2.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\birch15_3_hog.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\cannet.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\Firtree1.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\Flowers1.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\Flowers2.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\Flowers3.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\grass_triple_1.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\grass_triple_green2.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\hw_hge.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\leccio.ACE" .\Textures\Autumn\ /y
call Xcopy ".\Textures\lime19,22_1.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\Olivera_3.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\palmizi.ACE" .\Textures\Autumn\ /y
call Xcopy ".\Textures\Pi_pinyoner_0.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\Pi_pinyoner_4.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\Platan_1.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\siepe.ACE" .\Textures\Autumn\ /y
call Xcopy ".\Textures\siepever.ACE" .\Textures\Autumn\ /y
call Xcopy ".\Textures\treeL.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\vigne01.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\willow16_1.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\woody_species17_1.ace" .\Textures\Autumn\ /y
call Xcopy ".\Textures\Alzina_0.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\Alzina_1.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\arbrcha.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\betulla.ACE" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\BG_3.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\BG_3a.ACE" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\BG_6a.ACE" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\birch15_1_hog.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\birch15_2.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\birch15_3_hog.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\cannet.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\Firtree1.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\Flowers1.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\Flowers2.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\Flowers3.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\grass_triple_1.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\grass_triple_green2.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\hw_hge.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\leccio.ACE" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\lime19,22_1.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\Olivera_3.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\palmizi.ACE" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\Pi_pinyoner_0.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\Pi_pinyoner_4.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\Platan_1.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\siepe.ACE" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\siepever.ACE" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\vigne01.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\willow16_1.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\woody_species17_1.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\abete.ACE" .\Textures\Spring\ /y
call Xcopy ".\Textures\albur.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\Alzina_0.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\Alzina_1.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\arbrcha.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\betulla.ACE" .\Textures\Spring\ /y
call Xcopy ".\Textures\BG_3.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\BG_3a.ACE" .\Textures\Spring\ /y
call Xcopy ".\Textures\BG_6a.ACE" .\Textures\Spring\ /y
call Xcopy ".\Textures\birch15_1_hog.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\birch15_2.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\birch15_3_hog.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\cannet.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\carrubo.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\castanea.ACE" .\Textures\Spring\ /y
call Xcopy ".\Textures\faggio.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\Firtree1.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\Flowers1.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\Flowers2.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\Flowers3.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\grass_triple_1.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\grass_triple_green2.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\hw_hge.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\leccio.ACE" .\Textures\Spring\ /y
call Xcopy ".\Textures\lime19,22_1.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\Olivera_3.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\palmizi.ACE" .\Textures\Spring\ /y
call Xcopy ".\Textures\Pi_pinyoner_0.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\Pi_pinyoner_4.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\Platan_1.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\platano.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\roverella.ACE" .\Textures\Spring\ /y
call Xcopy ".\Textures\siepe.ACE" .\Textures\Spring\ /y
call Xcopy ".\Textures\siepever.ACE" .\Textures\Spring\ /y
call Xcopy ".\Textures\sorbus.ACE" .\Textures\Spring\ /y
call Xcopy ".\Textures\vigne01.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\willow16_1.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\woody_species17_1.ace" .\Textures\Spring\ /y
call Xcopy ".\Textures\Alzina_0.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\Alzina_1.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\arbrcha.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\betulla.ACE" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\BG_3.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\BG_3a.ACE" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\BG_6a.ACE" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\birch15_1_hog.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\birch15_2.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\birch15_3_hog.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\cannet.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\Firtree1.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\Flowers1.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\Flowers2.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\Flowers3.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\grass_triple_1.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\grass_triple_green2.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\hw_hge.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\lime19,22_1.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\Olivera_3.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\palmizi.ACE" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\Pi_pinyoner_0.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\Pi_pinyoner_4.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\Platan_1.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\siepe.ACE" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\siepever.ACE" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\vigne01.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\willow16_1.ace" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\woody_species17_1.ace" .\Textures\SpringSnow\ /y
call Xcopy  ".\Textures\Alzina_0.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\Alzina_1.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\arbrcha.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\BG_3.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\BG_3a.ACE" .\Textures\Winter\ /y
call Xcopy  ".\Textures\BG_6a.ACE" .\Textures\Winter\ /y
call Xcopy  ".\Textures\birch15_1_hog.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\birch15_2.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\birch15_3_hog.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\cannet.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\Firtree1.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\Flowers1.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\Flowers2.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\Flowers3.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\grass_triple_1.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\grass_triple_green2.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\hw_hge.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\leccio.ACE" .\Textures\Winter\ /y
call Xcopy  ".\Textures\lime19,22_1.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\Olivera_3.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\palmizi.ACE" .\Textures\Winter\ /y
call Xcopy  ".\Textures\Pi_pinyoner_0.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\Pi_pinyoner_4.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\Platan_1.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\siepe.ACE" .\Textures\Winter\ /y
call Xcopy  ".\Textures\siepever.ACE" .\Textures\Winter\ /y
call Xcopy  ".\Textures\treeL.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\vigne01.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\willow16_1.ace" .\Textures\Winter\ /y
call Xcopy  ".\Textures\woody_species17_1.ace" .\Textures\Winter\ /y
call Xcopy ".\Textures\Alzina_0.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\Alzina_1.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\arbrcha.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\betulla.ACE" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\BG_3.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\BG_3a.ACE" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\BG_6a.ACE" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\birch15_1_hog.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\birch15_2.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\birch15_3_hog.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\cannet.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\Firtree1.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\Flowers1.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\Flowers2.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\Flowers3.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\grass_triple_1.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\grass_triple_green2.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\hw_hge.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\lime19,22_1.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\Olivera_3.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\palmizi.ACE" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\Pi_pinyoner_0.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\Pi_pinyoner_4.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\Platan_1.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\siepe.ACE" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\siepever.ACE" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\vigne01.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\willow16_1.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\woody_species17_1.ace" .\Textures\WinterSnow\ /y
call Xcopy ".\Textures\WinterSnow\carrubo.ACE" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\WinterSnow\roverella.ACE" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\WinterSnow\treeL.ace" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\WinterSnow\TREEMD.ACE" .\Textures\AutumnSnow\ /y
call Xcopy ".\Textures\WinterSnow\leccio.ACE" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\WinterSnow\roverella.ACE" .\Textures\SpringSnow\ /y
call Xcopy ".\Textures\WinterSnow\abete.ACE" .\Textures\Winter\ /y
call Xcopy ".\Textures\WinterSnow\TREEMD.ACE" .\Textures\Winter\ /y
